---
:max_retries: 2
:concurrency: 2
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
:timeout: 45
staging:
  :concurrency: 4
production:
  :concurrency: 4
:queues:
  - [default, 1]
  - [mailers, 1]
